### ISSUE TITLE
Update role on Ansible Galaxy.

### ISSUE THREAD

**Issue by ypid** [david415/ansible-tor#9]
https://galaxy.ansible.com/list#/roles/592
https://github.com/david415/ansible-tor/pull/8

**Comment by david415** [comment]
nusenu is now maintaining a fork of this project here:
https://github.com/nusenu/ansible-relayor

**Comment by ypid** [comment]
I [know](https://github.com/david415/ansible-tor/pull/8#issuecomment-133821442). I just wanted to request an update on Ansible Galaxy as well so that other people also find the new project.

**Comment by ypid** [comment]
Issue not yet solve. Please reopen.
